/* eslint-disable @conarti/feature-sliced/public-api */

import { IOffer } from '@/src/entities/offer';
import { EOfferBannerColors } from '@/src/entities/offer/model/banner-backgrounds';

export const OffersMockData: IOffer[] = [
  {
    id: 1,
    profit: 10,
    profitType: 'from',
    condition: {
      variant: 'amount',
      type: 'from_to',
      from_value: 1,
      to_value: 5,
    },
    banner_image: '/nurofen.png',
    banner_color: EOfferBannerColors.ORANGE,
    date_from: Date.now() - 86400000,
    date_to: Date.now() + 86400000,
    products: [
      {
        id: 3,
        brandId: 1,
        name: 'Нурофен таб. 20шт',
        fixCashback: 10,
        sku: '123612432',
        cashbackType: 'percent',
        brand: {
          id: 1,
          promotionId: 'x-pharm',
          name: 'Нурофен',
          description: 'Средство от головной боли',
          logo: '/nurofen_logo.png',
          createdAt: '123123412',
          updatedAt: '34324',
        },
      },
    ],
  },
  {
    id: 2,
    profit: 20,
    profitType: 'static',
    condition: {
      variant: 'price',
      type: 'from',
      from_value: 500,
    },
    banner_color: EOfferBannerColors.GREEN,
    banner_image: '/teraflu.png',
    date_from: Date.now() - 86400000,
    date_to: Date.now() + 86400000 * 30,
    products: [
      {
        id: 1,
        brandId: 3,
        name: 'Терафлю порошок 20пак.',
        fixCashback: 200,
        sku: '123412412',
        cashbackType: 'amount',
        brand: {
          id: 3,
          promotionId: 'x-pharm',
          name: 'Терафлю',
          description: 'Средство от головной боли',
          logo: '/theraflu_logo.png',
          createdAt: '123123412',
          updatedAt: '34324',
        },
      },
    ],
  },
  {
    id: 3,
    profit: 15,
    profitType: 'from',
    condition: {
      variant: 'amount',
      type: 'from',
      from_value: 2,
    },
    banner_image: '/grammidin.gif',
    banner_color: EOfferBannerColors.BLUE,
    date_from: Date.now() - 86400000,
    date_to: Date.now() + 86400000 * 10,
    products: [
      {
        id: 2,
        brandId: 2,
        name: 'Граммидин таб. 20шт',
        fixCashback: 20,
        sku: '123412432',
        cashbackType: 'percent',
        brand: {
          id: 2,
          promotionId: 'x-pharm',
          name: 'Граммидин',
          description: 'Средство от головной боли',
          logo: '/grammidin_logo.png',
          createdAt: '123123412',
          updatedAt: '34324',
        },
      },
    ],
  },
  {
    id: 4,
    profit: 30,
    profitType: 'static',
    banner_image: '/nurofen.png',
    banner_color: EOfferBannerColors.PURPLE,
    date_from: Date.now() - 86400000,
    date_to: Date.now() + 86400000,
    products: [
      {
        id: 1,
        brandId: 3,
        name: 'Терафлю порошок 20пак.',
        fixCashback: 200,
        sku: '123412412',
        cashbackType: 'amount',
        brand: {
          id: 3,
          promotionId: 'x-pharm',
          name: 'Терафлю',
          description: 'Средство от головной боли',
          logo: '/theraflu_logo.png',
          createdAt: '123123412',
          updatedAt: '34324',
        },
      },
      {
        id: 2,
        brandId: 2,
        name: 'Граммидин таб. 20шт',
        fixCashback: 20,
        sku: '123412432',
        cashbackType: 'percent',
        brand: {
          id: 2,
          promotionId: 'x-pharm',
          name: 'Граммидин',
          description: 'Средство от головной боли',
          logo: '/grammidin_logo.png',
          createdAt: '123123412',
          updatedAt: '34324',
        },
      },
      {
        id: 3,
        brandId: 1,
        name: 'Нурофен таб. 20шт',
        fixCashback: 10,
        sku: '123612432',
        cashbackType: 'percent',
        brand: {
          id: 1,
          promotionId: 'x-pharm',
          name: 'Нурофен',
          description: 'Средство от головной боли',
          logo: '/nurofen_logo.png',
          createdAt: '123123412',
          updatedAt: '34324',
        },
      },
      {
        id: 4,
        brandId: 1,
        name: 'Нурофен таб. 10шт',
        fixCashback: 100,
        sku: '122612432',
        cashbackType: 'amount',
        brand: {
          id: 1,
          promotionId: 'x-pharm',
          name: 'Нурофен',
          description: 'Средство от головной боли',
          logo: '/nurofen_logo.png',
          createdAt: '123123412',
          updatedAt: '34324',
        },
      },
      {
        id: 5,
        brandId: 4,
        name: 'Оциллококцинум кап. 10шт',
        fixCashback: 100,
        sku: '122612432',
        cashbackType: 'amount',
        brand: {
          id: 4,
          promotionId: 'x-pharm',
          name: 'Оциллококцинум',
          description: 'Средство от головной боли',
          logo: '/nurofen_logo.png',
          createdAt: '123123412',
          updatedAt: '34324',
        },
      },
    ],
  },
];
